### ISSUE TITLE
Division by zero exception found

### ISSUE THREAD

**Issue by radoslavpalenik** [kaito1410/AutoDD_Rev2#22]
Hi, 

found this exception by running script today(13:00 CET, 2020/1/26 on Win10).
```
Getting submissions...
Searching for tickers...
Populating results...
Counting rockets...
Getting quick stats...
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main()
  File "main.py", line 92, in main
    results_tbl = getQuickStats(results_tbl)
  File "C:\Users\Rado\Desktop\AutoDD\AutoDD_Rev2-main\AutoDD.py", line 489, in getQuickStats
    change_50day = ((float(price) - float(avg50day))/float(avg50day))*100
ZeroDivisionError: float division by zero
```

My temporal "fix" was:
```
 if price is not None and price != 0:
                if avg50day > 0:
                    change_50day = ((float(price) - float(avg50day))/float(avg50day))*100
                else:
                    change_50day = 0
```
on line 489 in `AutoDD.py`

**Comment by kaito1410** [comment]
Good catch, will add this in!

**Comment by kaito1410** [comment]
https://github.com/kaito1410/AutoDD_Rev2/pull/24
