### ISSUE TITLE
error if no selftext

### ISSUE THREAD

**Issue by gobbedy** [kaito1410/AutoDD_Rev2#27]
Me again :)

I just got this error:
```
Traceback (most recent call last):
  File "C:\Users\guillaume\PycharmProjects\AutoDD_Rev2\main.py", line 101, in <module>
    main()
  File "C:\Users\guillaume\PycharmProjects\AutoDD_Rev2\main.py", line 65, in main
    prev_tbl, prev_rockets = get_freq_list(results_from_api[1])
  File "C:\Users\guillaume\PycharmProjects\AutoDD_Rev2\AutoDD.py", line 171, in get_freq_list
    rocket_tickers = selftext_extracted.union(title_extracted)
UnboundLocalError: local variable 'selftext_extracted' referenced before assignment
```

I assume this happens when there is no selftext. Easy fix is to add the line pointed to below
```
        # search the text body for the ticker/tickers
        selftext_extracted = set()   # <------------- INSERT
        if hasattr(i, 'selftext'):
            selftext = ' ' + i.selftext + ' '
            selftext_extracted = set(re.findall(pattern, selftext))
```

**Comment by kaito1410** [comment]
Good catch, I also did the same for title_extracted just in case :) never know... https://github.com/kaito1410/AutoDD_Rev2/pull/29
